version: '3.9'
services:
  server:
    container_name: server
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ttd_test
  db:
    image: postgres:15-alpine
    ports:
      - '6543:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/data/db
    networks:
      - ttd_test
volumes:
  data:
networks:
  ttd_test:
    driver: bridge